name: ai4good
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - gdal
  - pytest
  - h5netcdf
  - matplotlib
  - panel
  - holoviews
  - plotly
  - xarray
  - geoviews
  - python==3.11.11
  - scikit-learn
  - pandas
  - tabulate
  - seaborn
  - ipykernel
  - nbstripout
  - scipy
  - hvplot
  - netcdf4
  - geopandas
  - shap
